spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskManager
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-16-digit-app-password  # No quotes needed for numeric password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

server:
  port: 8080

logging:
  level:
    root: INFO
    com.project.task.manager: DEBUG
    org.springframework.security: DEBUG